#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 15 11:36:47 2019

@author: 3535008
"""

def test(L):
    """list[int]->int"""
    #a: int
    a == 4
    if a % 2 == 0:
        return a
    else:
        a=3
    
    for i in range(a):
        a = a + 1
    
    print(a)
    return 1